export const CHAT_ACTIONS = {
    ADD_MESSAGE: "ADD_MESSAGE",
    DELETE_MESSAGE: "DELETE_MESSAGE",
    UPDATE_MESSAGE: "UPDATE_MESSAGE",
    CHANGE_STATUS: "CHANGE_STATUS",
};

export const MESSAGE_STATUSES = {
    SENDING: "SENDING",
    DONE: "DONE",
    FAILED: "FAILED",
};